FROM pytorch/pytorch:2.3.0-cpu

# Avoids interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies
RUN apt-get update && apt-get install -y \
    ffmpeg git build-essential \
    && rm -rf /var/lib/apt/lists/*

# Create app dir
WORKDIR /app

# Copy only requirements first
COPY requirements.txt .

# Install dependencies (torch already installed in base image)
RUN pip install --no-cache-dir -r requirements.txt

# Copy app code
COPY . .

# Expose Flask port
EXPOSE 8000

# Run your app
CMD ["gunicorn", "-b", "0.0.0.0:8000", "app:app"]
