# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# Docs for Azure Container Registry: https://github.com/Azure/docker-login
# More info: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - AI-NVC-Services

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_57F861F587164F668A5CFD861EFD4E99 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_896ED4FD7FA44342ACC9B0C1B26C2B36 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C094AC76D5934813BDB63BA7FC7B1039 }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: <YOUR_ACR_NAME>.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t <YOUR_ACR_NAME>.azurecr.io/ai-nvc-services:${{ github.sha }} .
          docker push <YOUR_ACR_NAME>.azurecr.io/ai-nvc-services:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_57F861F587164F668A5CFD861EFD4E99 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_896ED4FD7FA44342ACC9B0C1B26C2B36 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C094AC76D5934813BDB63BA7FC7B1039 }}

      - name: Deploy to Azure Web App (Container)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AI-NVC-Services'
          slot-name: 'Production'
          images: '<YOUR_ACR_NAME>.azurecr.io/ai-nvc-services:${{ github.sha }}'
